name: j2musicPro
favicon: null
layout_spectrum: 0.22371
typography_spectrum: 0.24683
title: Unlock the Power in your Music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7fdf3'
    - '#2d1c26'
    - '#a9937c'
    - '#cab99f'
    - '#886d5c'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
