layout_spectrum: 0.9318997
color:
  saturation: 1
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#E7E2C6'
    - '#4D5254'
    - '#FFFFFF'
    - '#0E0C0D'
    - '#2F2F31'
  rhythmicContrast: 0.734767
typography_spectrum: 0.5573477
name: j2musicPro
