name: j2musicPro
favicon: null
layout_spectrum: 1
typography_spectrum: 0.38565
title: 'Professional Music Production & Mixing '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ae8f66'
    - '#020003'
    - '#044e68'
    - '#e3bbba'
    - '#5d3b33'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
