name: j2musicPro
favicon: null
layout_spectrum: 0.93155
typography_spectrum: 0.5573477
title: 'Josh Woods: Musician, Mixer, Producer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#5b4e48'
    - '#7c7674'
    - '#023f10'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
