title: 'Professional Music Production & Mixing '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6218638
  brandStrength: 1
  lightness: 0.3172043
  brandColors:
    - '#35241C'
    - '#838F83'
    - '#FFFFF7'
    - '#E83D2B'
    - '#2568A3'
  rhythmicContrast: 0.5376344
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: j2musicPro
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.688172
layout_spectrum: 1
