name: j2musicPro
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5573477
title: Riding the wave of sound
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#5b4e48'
    - '#7c7674'
    - '#023f10'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
